# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-12-29 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191229_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 16, 1, 2, 506606, tzinfo=utc)),
        ),
    ]
